"us": "United States"
"usa": "United States"
"u.s.": "United States"
"u.s.a.": "United States"
"united states": "United States"
"america": "United States"
"uk": "United Kingdom"
"u.k.": "United Kingdom"
"britain": "United Kingdom"
"england": "United Kingdom"
"great britain": "United Kingdom"
"deutschland": "Germany"
"bundesrepublik deutschland": "Germany"
"deutschland/germany": "Germany"
"españa": "Spain"
"italia": "Italy"
"polska": "Poland"
"россия": "Russia"
"schweiz": "Switzerland"
"suisse": "Switzerland"
"svizzera": "Switzerland"
"中国": "China"
"日本": "Japan"
"भारत": "India"
"المملكة العربية السعودية": "Saudi Arabia"
"مصر": "Egypt"
"대한민국": "South Korea"
"ประเทศไทย": "Thailand"