# SPDX-FileCopyrightText: openmod-tracker contributors listed in AUTHORS.md
#
# SPDX-License-Identifier: CC0-1.0

adgefficiency.energy-py.stargazers: Y3Vyc29yOnYyOpK5MjAxOS0wOC0xOVQwMDozMDowOCswMTowMM4K5j3h
akkudoktor-eos.eos.forks: Y3Vyc29yOnYyOpK5MjAyNS0wNS0yOFQxMzo1OTowMyswMTowMM47II8d
akkudoktor-eos.eos.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMS0wOVQxMjo1MDowOSswMDowMM6lkSVJ
akkudoktor-eos.eos.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNi0yMVQxMTozNjowMSswMTowMM6bgVC_
akkudoktor-eos.eos.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNS0yN1QxMzo1NTo0OCswMTowMM4jXuT8
antaressimulatorteam.antares_simulator.issues: Y3Vyc29yOnYyOpK5MjAyMy0xMi0xOFQwOTo1Njo0MSswMDowMM559tz2
antaressimulatorteam.antares_simulator.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wMVQwOTowOToyNiswMTowMM6c16l9
arras-energy.gridlabd.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNi0wM1QyMDo0NDoxOCswMTowMM6K_hXN
arras-energy.gridlabd.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wNlQxODo1NTo0MiswMTowMM6dpayb
assume-framework.assume.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNi0yMFQwODo0Mjo0NiswMTowMM6M5A07
assume-framework.assume.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMS0zMVQxMDozNToyNiswMDowMM6JnRq1
blue-marble.gridpath.issues: Y3Vyc29yOnYyOpK5MjAyMi0xMi0xNlQxODo0NDoyNyswMDowMM5ZctW4
blue-marble.gridpath.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMy0xMFQxNToxOToyOSswMDowMM6OA4e1
blue-marble.gridpath.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0xMi0yN1QxMTo1MTo1NyswMDowMM4hGuxY
breakthrough-energy.reise.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMS0wNi0yNVQxNjo0MDowNiswMTowMM4oaZtD
calliope-project.calliope.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNi0yNFQxODoyMTo1MCswMTowMM6NTpTY
calliope-project.calliope.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wNi0yNVQxNDoyNjo1NyswMTowMM5zf-Fh
calliope-project.calliope.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0xMS0yMVQwOTozODo0NSswMDowMM4gmbBg
curent.andes.forks: Y3Vyc29yOnYyOpK5MjAyNC0xMS0xMlQwMDoyNzo0MyswMDowMM403jCH
curent.andes.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0wNC0yM1QxODoyNTo0NSswMTowMM42rA1u
curent.andes.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wNS0xNVQxMjoyMDo1NCswMTowMM4d2NaE
dpinney.omf.issues: Y3Vyc29yOnYyOpK5MjAxNS0wMi0wNFQxNjoxNDoxNSswMDowMM4DXtrq
dpinney.omf.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0wMy0xN1QxNTowODoyMiswMDowMM4X2kDD
dss-extensions.dss_capi.issues: Y3Vyc29yOnYyOpK5MjAyMi0wNy0yMVQxOTozNTowMyswMTowMM5OTLRx
dynawo.dynawo.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNy0yNVQwODo0ODozNyswMTowMM7Ccy4C
dynawo.dynawo.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0wOVQxNToyOTowNyswMTowMM6R9XlV
e2niee.pandapower.forks: Y3Vyc29yOnYyOpK5MjAyNS0wOC0wNVQxNjo1Nzo0MCswMTowMM49jPJr
e2niee.pandapower.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMS0wOVQxMzo0Mjo1NyswMDowMM6lkxRf
e2niee.pandapower.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0wNFQwOTozOTo1MCswMTowMM6RXuY_
e2niee.pandapower.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNy0yM1QyMzo0MDo1MSswMTowMM4kMlyX
electa-git.flexplan.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0wMi0yM1QwNzoyODowMSswMDowMM4zU6B4
energyinnovation.eps-us.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNC0yM1QxOTo0ODowMyswMTowMM6GrghI
energysystemsmodellinglab.muse_os.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNy0xNVQxNDo0ODoxOSswMTowMM7AqaBj
energysystemsmodellinglab.muse_os.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNi0wMlQxMjo1NzoxNiswMTowMM6YnFbO
erf-model.erf.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wOC0wOVQwMTozMjozNyswMTowMM6i1u0v
etsap-times.times_model.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wOC0yOFQxMDo1NjoxNiswMTowMM4fcIdl
flexiblepower.powermatcher.issues: Y3Vyc29yOnYyOpK5MjAxNC0xMi0wMlQxMDozMzoyNyswMDowMM4DBKCc
flixopt.flixopt.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMy0wNlQwODowMTowNSswMDowMM6NmZGC
genxproject.genx.jl.forks: Y3Vyc29yOnYyOpK5MjAyNC0wNi0yNVQxNjoxODoyMCswMTowMM4w4Alw
genxproject.genx.jl.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNC0yOFQyMzowNzoyOSswMTowMM60YoUR
genxproject.genx.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wOS0yM1QyMjo1NjowMiswMTowMM58bnWX
genxproject.genx.jl.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xN1QyMzo1NzozMCswMTowMM4izvMl
gmlc-dispatches.dispatches.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0wOC0yM1QwMDozMzoxMiswMTowMM49mXZ1
gmlc-tdc.helics.issues: Y3Vyc29yOnYyOpK5MjAyMi0xMS0xNlQxNzoxMjoxMSswMDowMM5Wi1vQ
gmlc-tdc.helics.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0xMi0wM1QxOToyODozNSswMDowMM6D78JZ
gmlc-tdc.helics.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0xMS0xNFQxNToxNDo0MCswMDowMM4bTdfn
grid-parity-exchange.egret.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0wNC0wNVQyMDo0ODo0NyswMTowMM41rvTp
grid-parity-exchange.egret.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0wMi0yN1QxNDo0NzoyMSswMDowMM4XU1k3
grid2op.grid2op.forks: Y3Vyc29yOnYyOpK5MjAyNC0wNC0xOVQwNzozNzo0MCswMTowMM4vBHQa
grid2op.grid2op.issues: Y3Vyc29yOnYyOpK5MjAyMy0wOS0yOFQyMjowNDozNiswMTowMM5yVoHe
grid2op.grid2op.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMi0yNVQyMDo0NzoxOSswMDowMM6MiA0p
grid2op.grid2op.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0xMi0yMFQwODowOTowNiswMDowMM4hAnkr
gridoptics.gridpack.issues: Y3Vyc29yOnYyOpK5MjAyMy0wMy0xNlQxNDowNzozOCswMDowMM5hAr_9
gridoptics.gridpack.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNi0wNFQxODozNjozNiswMTowMM6ZEKWr
idaholab.heron.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNi0wNFQxOTowNTozOCswMTowMM654u0q
idaholab.heron.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0xMC0xOFQxODo1NTozMiswMTowMM5BCZte
ie3-institute.powersystemdatamodel.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMy0wNVQwNzo0NzoxNCswMDowMM6spWFw
ie3-institute.powersystemdatamodel.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNS0wOFQxMzoxMDo0OSswMTowMM6VbOHC
ie3-institute.simona.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNS0xOVQxMzo1MToxOSswMTowMM63NYdC
ie3-institute.simona.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNi0yNFQwNTo1MDo1NCswMTowMM6bxonH
irena-flextool.flextool.issues: Y3Vyc29yOnYyOpK5MjAyMy0xMi0yMlQxNTo0MzoyMSswMDowMM56bwAf
juliaenergy.powerdynamics.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMS0wNC0yM1QwMTozMDo0NSswMTowMM4lDhg5
juliaenergy.powerdynamics.jl.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wOC0wOFQyMjo1MDowNCswMTowMM4fKtrw
lanl-ansi.powermodels.jl.forks: Y3Vyc29yOnYyOpK5MjAyMi0wOC0xNFQyMToxMzowOCswMTowMM4fR1vE
lanl-ansi.powermodels.jl.issues: Y3Vyc29yOnYyOpK5MjAyMS0wMS0yNlQwMTo0MDo1OSswMDowMM4vUUYA
lanl-ansi.powermodels.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0wOC0wN1QwNDozNjo1NyswMTowMM48w7ph
lanl-ansi.powermodels.jl.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wMS0wN1QxMjo1MDo1OSswMDowMM4hQZEC
lkruitwagen.global-fossil-fuel-supply-chain.stargazers: Y3Vyc29yOnYyOpK5MjAyMi0wNy0wNFQwMTowNjo1OCswMTowMM4Ui0j9
marvinler.pypownet.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0xMC0wNlQyMjozOTowNCswMTowMM4a10BR
matpower.matpower.forks: Y3Vyc29yOnYyOpK5MjAyMS0wOC0xOVQxNDo1MzowNSswMTowMM4XuGSP
matpower.matpower.issues: Y3Vyc29yOnYyOpK5MjAyNC0wOC0yMVQxNzowODo1NyswMTowMM6Tud3z
matpower.matpower.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wNy0xMVQwOTozNToxMiswMTowMM4etMuP
nrel-sienna.powersimulations.jl.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNC0wMVQxMToyOToyNCswMTowMM6wm_x6
nrel-sienna.powersimulations.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0yMlQwODowOTowNCswMTowMM6gANd9
nrel-sienna.powersimulations.jl.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0wMy0yNFQxNjowNDoxMyswMDowMM4YCs8l
nrel-sienna.powersimulationsdynamics.jl.issues: Y3Vyc29yOnYyOpK5MjAyMi0wNy0yN1QyMDo1OToyMCswMTowMM5Oro7G
nrel-sienna.powersimulationsdynamics.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMy0wNi0yOFQwNDozNDo1NSswMTowMM5UGP_d
nrel-sienna.powersimulationsdynamics.jl.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNi0wM1QxMzo1Mjo1NyswMTowMM4jd_z0
nrel.h2integrate.issues: Y3Vyc29yOnYyOpK5MjAyNS0wOC0wNFQxOTowMTozMyswMTowMM7EHpZ3
nrel.h2integrate.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wOC0wN1QyMjo0Nzo0OCswMTowMM6iqhuh
nrel.hopp.issues: Y3Vyc29yOnYyOpK5MjAyNC0xMC0yMVQxODoxODo1MSswMTowMM6bKbLu
nrel.hopp.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMi0xN1QyMToxNzozMyswMDowMM6Lguba
nrel.pysam.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNC0yNFQyMzoyOTo0MiswMTowMM6G18t5
nrel.pysam.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wOC0wOFQyMDowMDoyNCswMTowMM4fKnZf
nrel.reeds-2.0.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wMS0yOVQyMToyNToxOCswMDowMM4cRbI4
nrel.reopt.jl.issues: Y3Vyc29yOnYyOpK5MjAyMy0xMC0wOVQxODowNTowMSswMTowMM5zPn-O
nrel.reopt.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wOC0wOVQyMToxOTo0OCswMTowMM53_BrW
nrel.reopt_api.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wNS0wNlQyMTo0MjozNyswMTowMM5urpBs
nrel.reopt_api.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xNlQwMDo0MjozNCswMTowMM4ixpde
nrel.reopt_lite_api.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wNS0wNlQyMTo0MjozNyswMTowMM5urpBs
nrel.reopt_lite_api.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xNlQwMDo0MjozNCswMTowMM4ixpde
nrel.sam.forks: Y3Vyc29yOnYyOpK5MjAyMi0xMC0xNlQxNDozNTo0NCswMTowMM4g7MQ4
nrel.sam.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMi0xOVQyMjo1NjoyMSswMDowMM6qvdYj
nrel.sam.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMS0yM1QxNzozNjo1NSswMDowMM6Iy545
nrel.sam.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNy0yOVQxNDo1MjoyOSswMTowMM4kRrAC
oemof.oemof-solph.forks: Y3Vyc29yOnYyOpK5MjAyMy0wNS0yNlQwOTo1NzowMiswMTowMM4mfLcF
oemof.oemof-solph.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMi0yOFQxNDowOToxNiswMDowMM6sF_7g
oemof.oemof-solph.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wMi0xNlQxNToxOToyNiswMDowMM5nGWaN
oemof.oemof-solph.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0xMi0xNVQwOTowNDo1OSswMDowMM4g7vfH
oemof.oemof-thermal.pullRequests: Y3Vyc29yOnYyOpK5MjAyMS0wMi0xMVQxMzoxMTozNCswMDowMM4iFRbX
openego.edisgo.issues: Y3Vyc29yOnYyOpK5MjAyMi0wOS0yMlQxNDo0OToxOSswMTowMM5SZxYG
openego.edisgo.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMS0zMFQwOTo1OToyNiswMDowMM6JeexD
openego.ego.pullRequests: Y3Vyc29yOnYyOpK5MjAxOC0xMi0wN1QxMjozMjozMiswMDowMM4OHhnm
openipsl.openipsl.issues: Y3Vyc29yOnYyOpK5MjAyMi0wNS0yN1QxNTowNzo0OSswMTowMM5KjeX7
openipsl.openipsl.pullRequests: Y3Vyc29yOnYyOpK5MjAyMi0xMC0wOVQyMDo0Njo0NSswMTowMM5AdBm7
osemosys.osemosys.forks: Y3Vyc29yOnYyOpK5MjAyNC0xMC0xNlQwODo1NDoyMSswMTowMM40D_AC
osemosys.osemosys.stargazers: Y3Vyc29yOnYyOpK5MjAyMi0wNC0xNFQxMjo0OTo1OCswMTowMM4Tr9r1
pnnl.tesp.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNC0xMlQwMDoxMzoxMCswMTowMM6FcLcM
powergridmodel.power-grid-model.issues: Y3Vyc29yOnYyOpK5MjAyNC0xMi0wNlQwODoyNDoyMSswMDowMM6iRFdh
powergridmodel.power-grid-model.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0xNlQwOToxNDozNyswMTowMM6fIeq8
powergridmodel.power-grid-model.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wMS0zMFQxMDo1Mzo0NyswMDowMM4cR8eG
powsybl.powsybl-core.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNy0yMVQxNDowMzoxOSswMTowMM7BoY9-
powsybl.powsybl-core.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wMlQxMTo1OTo1OCswMTowMM6dEEgm
powsybl.powsybl-core.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0wNi0xMlQxNzowNTowNCswMTowMM4ZWfD3
powsybl.powsybl-open-loadflow.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNC0wNVQxMzowNDoyMSswMTowMM6Eyp7R
powsybl.powsybl-open-loadflow.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0wOFQxMDo1NzoxNSswMTowMM6Rwl8z
powsybl.pypowsybl.issues: Y3Vyc29yOnYyOpK5MjAyNC0xMS0xM1QwODoyMTo0MiswMDowMM6eOpFN
powsybl.pypowsybl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0xMVQxMDoxMTo0NiswMTowMM6edSEO
prep-next.prep-shot.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0xMC0zMFQwOTozOTozMSswMDowMM4gSDYx
pypsa.pypsa.forks: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xNVQwMzowNDoyMiswMTowMM45m2b0
pypsa.pypsa.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wMlQxNjozMToyNCswMTowMM6-hAKj
pypsa.pypsa.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0yMlQwOTozOToxNSswMTowMM6TZs3K
pypsa.pypsa.stargazers: Y3Vyc29yOnYyOpK5MjAyNS0wNy0zMVQwODoxODo1OCswMTowMM4kTY_h
quintel.etengine.issues: Y3Vyc29yOnYyOpK5MjAyNC0wNi0yNlQxMToyNDozMCswMTowMM6Njvwb
quintel.etengine.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xMFQwOTozNjo1OCswMTowMM6SDzt4
quintel.etmodel.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMS0yOVQxNDo1NDowOCswMDowMM6n_iVn
quintel.etmodel.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMi0yMFQxNTo0MDoxMiswMDowMM6L62V7
rl-institut.multi-vector-simulator.issues: Y3Vyc29yOnYyOpK5MjAyMS0wMi0wMVQxNjo0OTowNyswMDowMM4vmI97
rl-institut.multi-vector-simulator.pullRequests: Y3Vyc29yOnYyOpK5MjAyMS0wMy0wNFQxMDowODoyMyswMDowMM4i2WlP
rwl.pypower.forks: Y3Vyc29yOnYyOpK5MjAyNC0wMS0wOVQwNjo0NzoxMyswMDowMM4sKDQm
rwl.pypower.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wMy0xM1QwODo1OTozNCswMDowMM4c5WDp
sanpen.gridcal.forks: Y3Vyc29yOnYyOpK5MjAyNS0wMi0yNFQxNzoxMjowMSswMDowMM437LrC
sanpen.gridcal.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMy0xNFQwNzo1OTo0NiswMDowMM6uA3JP
sanpen.gridcal.pullRequests: Y3Vyc29yOnYyOpK5MjAyMy0wNS0yNVQxOTowMjoyMiswMTowMM5RXkFB
sanpen.gridcal.stargazers: Y3Vyc29yOnYyOpK5MjAyNC0wOS0wMlQxMjo1ODoyOSswMTowMM4fgZMy
slacgismo.tess.pullRequests: Y3Vyc29yOnYyOpK5MjAyMS0wNi0xN1QwMjo0MTo1NyswMTowMM4oDy8S
sogno-platform.dpsim.issues: Y3Vyc29yOnYyOpK5MjAyMy0xMC0yMVQxMjowOToxNyswMTowMM50jbcc
sogno-platform.dpsim.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMi0wNlQyMToxMjo0NiswMDowMM6KVgiR
spine-tools.spineopt.jl.issues: Y3Vyc29yOnYyOpK5MjAyNC0wOS0zMFQxNjoyOTo1OCswMTowMM6YaPBY
spine-tools.spineopt.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNC0wOS0yM1QxMDo0MjozMyswMTowMM58V0ls
switch-model.switch.pullRequests: Y3Vyc29yOnYyOpK5MjAxOS0xMC0wNFQxOTowNDo0NiswMTowMM4TW-lO
switch-model.switch.stargazers: Y3Vyc29yOnYyOpK5MjAyMy0wMi0wOVQyMzoyNDo1MSswMDowMM4XBbm_
tulipaenergy.tulipaenergymodel.jl.issues: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wOVQxMToyMjowMSswMTowMM6_pwxY
tulipaenergy.tulipaenergymodel.jl.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNy0wN1QwNjoxMTo0NiswMTowMM6drxbC
tum-ens.urbs.forks: Y3Vyc29yOnYyOpK5MjAyMi0wMy0yNFQxMTowNTozMCswMDowMM4cOhjD
tum-ens.urbs.issues: Y3Vyc29yOnYyOpK5MjAxOS0wNC0wMVQxMjowODo1NCswMTowMM4ZfVdA
tum-ens.urbs.pullRequests: Y3Vyc29yOnYyOpK5MjAxNy0xMi0wOFQxMjowNzoxMyswMDowMM4JXx13
tum-ens.urbs.stargazers: Y3Vyc29yOnYyOpK5MjAyMC0wOS0xOVQwMzoyMToxMCswMTowMM4OOXYl
uu-er.adopt-net0.issues: Y3Vyc29yOnYyOpK5MjAyNC0xMC0wN1QwODowODoyNSswMTowMM6ZKCAl
uu-er.adopt-net0.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNi0xNlQxMjozNDo1OSswMTowMM6aswlG
villasframework.node.issues: Y3Vyc29yOnYyOpK5MjAyMi0wOC0xMFQxNjo1OTozMiswMTowMM5XxyD_
villasframework.node.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wNC0xNlQxMTo1OTozNiswMTowMM6S0h2U
zen-universe.zen-garden.issues: Y3Vyc29yOnYyOpK5MjAyNS0wMS0wNlQxNjoxMDoxMiswMDowMM6lKbvp
zen-universe.zen-garden.pullRequests: Y3Vyc29yOnYyOpK5MjAyNS0wMy0wNFQxNzowNDozOCswMDowMM6NWM7Y
