builtins = ["snakemake"]
target-version = "py312"

[format]
skip-magic-trailing-comma = true

[lint]
select = ["E", "F", "I", "Q", "W", "D", "PT", "UP"]
# line too long; Black will handle these
ignore = ["E501"]

[lint.isort]
split-on-trailing-comma = false

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

# Ignore `E402` (import violations) and `F401` (unused imports) in all `__init__.py` files
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "D104"]

[lint.flake8-quotes]
docstring-quotes = "double"

[lint.pydocstyle]
convention = "google"
